# Generated by Django 5.1.3 on 2024-11-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fech', models.DateField()),
                ('id_Cliente', models.SmallIntegerField()),
                ('costo', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField()),
            ],
        ),
    ]
